commands more generalized and parallelized

diff --git a/experiment/Makefile b/experiment/Makefile
--- a/experiment/Makefile
+++ b/experiment/Makefile
@@ -1,7 +1,6 @@
 HUMAN_V38_FASTA := human_v38.fasta
 PBSIM_MAF := *.maf.gz
 PBSIM_FASTQ := *.fastq.gz
-PREFIX := sd_merged_
 LCP_LEVEL := 4
 
 # Programs
@@ -9,9 +8,12 @@ CPP_LCP_FASTA := cpp-lcp-fasta
 CPP_LCP_FASTQ_ERROR := cpp-lcp-fastq-error
 CPP_MINIMIZER_FASTA := cpp-minimizer-fasta
 CPP_MINIMIZER_FASTQ_ERROR := cpp-minimizer-fastq-error
-PROCESS_MAF := process-maf
-FASTQ_TO_FASTQ := fastq-to-fasta
+FASTQ_TO_FASTA := fastq-to-fasta
 GOLD_STANDARD_GFA := gold-standard-gfa
+LCP_TRIE_BASED := lcp-trie-based-stat
+LCP_INVERTED_BASED := lcp-inverted-based
+COMPARE_GFA := compare-gfa
+EXTRACT_CHROM := extract-chrom
 
 # Directories
 CURRENT_DIR := $(shell pwd)
@@ -19,11 +21,6 @@ DATA_DIR := $(CURRENT_DIR)/../data
 EXECUTABLE_DIR := $(CURRENT_DIR)/../bin
 RESULTS_DIR := $(CURRENT_DIR)/../results
 OUT_DIR := $(CURRENT_DIR)/../out
-
-# Data paths
-HUMAN_V38_FASTA_PATH := $(DATA_DIR)/$(HUMAN_V38_FASTA)
-PBSIM_MAF_PATH := $(DATA_DIR)/$(PBSIM_MAF)
-PBSIM_FASTQ_PATH := $(DATA_DIR)/$(PBSIM_FASTQ)
 
 # Extension
 CXX := .cpp
@@ -64,17 +61,17 @@ MKDIR_OUT:
 	fi
 
 TEST_DATA:
-	@if [ ! -f $(HUMAN_V38_FASTA_PATH) ]; then \
-		echo "File $(HUMAN_V38_FASTA_PATH) does not exist. Exiting."; \
+	@if [ ! -f $(DATA_DIR)/$(HUMAN_V38_FASTA) ]; then \
+		echo "File $(DATA_DIR)/$(HUMAN_V38_FASTA) does not exist. Exiting."; \
 		exit 1; \
 	fi
-	@echo "File $(HUMAN_V38_FASTA_PATH) exists."
-	@if ! ls $(PBSIM_MAF_PATH) 1> /dev/null; then \
+	@echo "File $(DATA_DIR)/$(HUMAN_V38_FASTA) exists."
+	@if ! ls $(DATA_DIR)/$(PBSIM_MAF) 1> /dev/null; then \
 		echo "No .maf.gz files found. Exiting."; \
 		exit 1; \
 	fi
 	@echo "At least one maf.gz file exists."
-	@if ! ls $(PBSIM_FASTQ_PATH) 1> /dev/null; then \
+	@if ! ls $(DATA_DIR)/$(PBSIM_FASTQ) 1> /dev/null; then \
 		echo "No .fastq.gz files found. Exiting."; \
 		exit 1; \
 	fi
@@ -83,86 +80,107 @@ TEST_DATA:
 ######################################################################
 # HELPERS
 ######################################################################
-processMaf: MKDIR_BIN MKDIR_RESULTS
-	@echo "Compiling $(PROCESS_MAF)$(CXX)"
-	$(GXX) -o $(PROCESS_MAF) $(PROCESS_MAF)$(CXX) -lz
-	@echo "Moving $(PROCESS_MAF) to $(EXECUTABLE_DIR)"
-	mv $(PROCESS_MAF) $(EXECUTABLE_DIR)
-	@echo "Processing files in parallel"
-	@find $(DATA_DIR) -name '$(PREFIX)*.maf.gz' | parallel ' \
-		file=$$(basename {}); \
-		pname=$$(echo $$file | sed 's/\.maf.gz/_processed.maf.gz/'); \
-		out_file=$(PROCESS_MAF)-$${file#$(PREFIX)}; \
-		out_file=$$(echo $$out_file | sed 's/\.maf.gz/-out.txt/'); \
-		echo "Processing $${file}" > $(OUT_DIR)/$${out_file}; \
-		if [ -f $(RESULTS_DIR)/$${pname} ]; then \
-			echo "Removing existing processed file $(RESULTS_DIR)/$${pname}" >> $(OUT_DIR)/$${out_file}; \
-			rm -f $(RESULTS_DIR)/$${pname}; \
-		fi; \
-		echo "Preprocessing $${file}. Output will be put into $(RESULTS_DIR)/$${pname}" >> $(OUT_DIR)/$${out_file}; \
-		$(TIME) $(EXECUTABLE_DIR)/$(PROCESS_MAF) {} $(RESULTS_DIR)/$${pname} >> $(OUT_DIR)/$${out_file} 2>&1 \
-	'
-
-fastqToFastq: MKDIR_BIN MKDIR_RESULTS
-	@echo "Compiling $(FASTQ_TO_FASTQ)$(CXX)"
-	$(GXX) -o $(FASTQ_TO_FASTQ) $(FASTQ_TO_FASTQ)$(CXX) -lz
-	@echo "Moving $(FASTQ_TO_FASTQ) to $(EXECUTABLE_DIR)"
-	mv $(FASTQ_TO_FASTQ) $(EXECUTABLE_DIR)
-	@find $(DATA_DIR) -name '$(PREFIX)*.fastq.gz' | parallel ' \
+fastqToFasta: MKDIR_BIN MKDIR_RESULTS
+	@echo "Compiling $(FASTQ_TO_FASTA)$(CXX)";
+	$(GXX) -Wall -o $(FASTQ_TO_FASTA) $(FASTQ_TO_FASTA)$(CXX) -lz;
+	@echo "Moving $(FASTQ_TO_FASTA) to $(EXECUTABLE_DIR)";
+	mv $(FASTQ_TO_FASTA) $(EXECUTABLE_DIR);
+	@find $(DATA_DIR) -name '$(PBSIM_FASTQ)' | parallel ' \
 		file=$$(basename {}); \
 		rname=$$(echo $$file | sed 's/\.fastq.gz/.fasta.gz/'); \
-		out_file=$(FASTQ_TO_FASTQ)-$${file#$(PREFIX)}; \
-		out_file=$$(echo $$out_file | sed 's/\.fastq.gz/-out.txt/'); \
+		out_file=$(FASTQ_TO_FASTA)-$$(echo $$file | sed 's/\.fastq.gz/-out.txt/'); \
 		echo "Processing $$file" > $(OUT_DIR)/$${out_file}; \
 		if [ -f $(RESULTS_DIR)/$$rname ]; then \
 			echo "Removing existing processed file $(RESULTS_DIR)/$$rname" >> $(OUT_DIR)/$${out_file}; \
 			rm -f $(RESULTS_DIR)/$$rname; \
         fi; \
 		echo "Preprocessing $$file. Output will be put into $(RESULTS_DIR)/$$rname" >> $(OUT_DIR)/$${out_file}; \
-		$(TIME) $(EXECUTABLE_DIR)/$(FASTQ_TO_FASTQ) {} $(RESULTS_DIR)/$$rname >> $(OUT_DIR)/$${out_file} 2>&1 \
+		$(TIME) $(EXECUTABLE_DIR)/$(FASTQ_TO_FASTA) {} $(RESULTS_DIR)/$$rname >> $(OUT_DIR)/$${out_file} 2>&1 \
 	'
 
 goldStandartGfa: MKDIR_BIN MKDIR_RESULTS
-	@echo "Compiling $(GOLD_STANDARD_GFA)$(CXX)"
-	$(GXX) -o $(GOLD_STANDARD_GFA) $(GOLD_STANDARD_GFA)$(CXX) -lz
-	@echo "Moving $(GOLD_STANDARD_GFA) to $(EXECUTABLE_DIR)"
-	mv $(GOLD_STANDARD_GFA) $(EXECUTABLE_DIR)
-	@find $(DATA_DIR) -name '$(PREFIX)*_processed.maf.gz' | parallel ' \
+	@echo "Compiling $(GOLD_STANDARD_GFA)$(CXX)";
+	$(GXX) -Wall -o $(GOLD_STANDARD_GFA) $(GOLD_STANDARD_GFA)$(CXX) -lz;
+	@echo "Moving $(GOLD_STANDARD_GFA) to $(EXECUTABLE_DIR)";
+	mv $(GOLD_STANDARD_GFA) $(EXECUTABLE_DIR);
+	@find $(DATA_DIR) -name '$(PBSIM_MAF)' | parallel ' \
 		file=$$(basename {}); \
-		rname=$$(echo $$file | sed 's/\.maf.gz/.gfa/'); \
-		out_file=$(GOLD_STANDARD_GFA)-$${file#$(PREFIX)}; \
-		out_file=$$(echo $$out_file | sed 's/\_processed.maf.gz/-out.txt/'); \
+		rname=$$(echo $$file | sed 's/\.maf.gz/_gold.gfa/'); \
+		out_file=$(GOLD_STANDARD_GFA)-$$(echo $$file | sed 's/\.maf.gz/-out.txt/'); \
 		echo "Processing $$file" > $(OUT_DIR)/$${out_file};  \
 		if [ -f $(RESULTS_DIR)/$$rname ]; then \
 			echo "Removing existing processed file $(RESULTS_DIR)/$$rname" >> $(OUT_DIR)/$${out_file}; \
 			rm -f $(RESULTS_DIR)/$$rname; \
         fi; \
 		echo "Preprocessing $$file. Output will be put into $(RESULTS_DIR)/$$rname" >> $(OUT_DIR)/$${out_file}; \
-		$(TIME) $(EXECUTABLE_DIR)/$(GOLD_STANDARD_GFA) {} $(RESULTS_DIR)/$$rname >> $(OUT_DIR)/$${out_file}; \
+		$(TIME) $(EXECUTABLE_DIR)/$(GOLD_STANDARD_GFA) {} $(RESULTS_DIR)/$$rname --simple >> $(OUT_DIR)/$${out_file} 2>&1 \
 	'
 
 ######################################################################
 # LCP
 ######################################################################
 lcpFasta: MKDIR_BIN MKDIR_RESULTS
-	$(GXX) -o $(CPP_LCP_FASTA) $(CPP_LCP_FASTA)$(CXX); \
-	mv $(CPP_LCP_FASTA) $(EXECUTABLE_DIR); \
-	$(TIME) $(EXECUTABLE_DIR)/$(CPP_LCP_FASTA) $(HUMAN_V38_FASTA_PATH) > $(RESULTS_DIR)/$(CPP_LCP_FASTA)-output.txt
+	@echo "Compiling $(CPP_LCP_FASTA)$(CXX)";
+	$(GXX) -Wall -o $(CPP_LCP_FASTA) $(CPP_LCP_FASTA)$(CXX);
+	@echo "Moving $(CPP_LCP_FASTA) to $(EXECUTABLE_DIR)";
+	mv $(CPP_LCP_FASTA) $(EXECUTABLE_DIR);
+	@echo "Preprocessing $(HUMAN_V38_FASTA_PATH). Output will be put into $(RESULTS_DIR)/$(CPP_LCP_FASTA)-output.txt"; \
+	$(TIME) $(EXECUTABLE_DIR)/$(CPP_LCP_FASTA) $(HUMAN_V38_FASTA_PATH) > $(RESULTS_DIR)/$(CPP_LCP_FASTA)-output.txt 2>&1;
 
 lcpFastq: MKDIR_BIN MKDIR_RESULTS
-	$(GXX) -o $(CPP_LCP_FASTQ_ERROR) $(CPP_LCP_FASTQ_ERROR)$(CXX); \
-	mv $(CPP_LCP_FASTQ_ERROR) $(EXECUTABLE_DIR); \
-	$(TIME) $(EXECUTABLE_DIR)/$(CPP_LCP_FASTQ_ERROR) $(PBSIM_MAF_PROCESSED) $(LCP_LEVEL)
+	@echo "Compiling $(CPP_LCP_FASTQ_ERROR)$(CXX)";
+	$(GXX) -Wall -o $(CPP_LCP_FASTQ_ERROR) $(CPP_LCP_FASTQ_ERROR)$(CXX) -lz
+	@echo "Moving $(CPP_LCP_FASTQ_ERROR) to $(EXECUTABLE_DIR)";
+	mv $(CPP_LCP_FASTQ_ERROR) $(EXECUTABLE_DIR);
+	parallel "$(TIME) $(EXECUTABLE_DIR)/$(CPP_LCP_FASTQ_ERROR) $(DATA_DIR)/sd_merged_"{1}".maf.gz "{2}" > $(RESULTS_DIR)/$(CPP_LCP_FASTQ_ERROR)-"{1}"-"{2}".txt 2>&1" ::: 85 90 95 99 ::: 2 3 4 5 6 7
 
 ######################################################################
 # MINIMIZER
 ######################################################################
 minimizerFasta: MKDIR_BIN MKDIR_RESULTS
-	$(GXX) -o $(CPP_MINIMIZER_FASTA) $(CPP_MINIMIZER_FASTA)$(CXX) && \
-	mv $(CPP_MINIMIZER_FASTA) $(EXECUTABLE_DIR) && \
-	$(TIME) $(EXECUTABLE_DIR)/$(CPP_MINIMIZER_FASTA) $(HUMAN_V38_FASTA_PATH) > $(RESULTS_DIR)/$(CPP_MINIMIZER_FASTA)-output.txt 2>&1;
+	@echo "Compiling $(CPP_MINIMIZER_FASTA)$(CXX)";
+	$(GXX) -Wall -g -o $(CPP_MINIMIZER_FASTA) $(CPP_MINIMIZER_FASTA)$(CXX);
+	@echo "Moving $(CPP_MINIMIZER_FASTA) to $(EXECUTABLE_DIR)";
+	mv $(CPP_MINIMIZER_FASTA) $(EXECUTABLE_DIR);
+	parallel --link "$(TIME) $(EXECUTABLE_DIR)/$(CPP_MINIMIZER_FASTA)" "$(HUMAN_V38_FASTA_PATH)" {1} {2} ">" "$(RESULTS_DIR)/$(CPP_MINIMIZER_FASTA)-k{1}-w{2}.txt 2>&1;"  ::: 4 10 16 ::: 8 20 32
 
 minimizerFastq: MKDIR_BIN MKDIR_RESULTS
-	$(GXX) -o $(CPP_MINIMIZER_FASTQ_ERROR) $(CPP_MINIMIZER_FASTQ_ERROR)$(CXX) && \
-	mv cpp-minimizer-fastq-error ../bin && \
-	time ../bin/cpp-minimizer-fastq-error ~/data/pbsim/sd_0001.maf > ../results/output.minimizer.fastq.pbsim.txt
+	@echo "Compiling $(CPP_MINIMIZER_FASTQ_ERROR)$(CXX)";
+	$(GXX) -Wall -o $(CPP_MINIMIZER_FASTQ_ERROR) $(CPP_MINIMIZER_FASTQ_ERROR)$(CXX);
+	@echo "Moving $(CPP_MINIMIZER_FASTQ_ERROR) to $(EXECUTABLE_DIR)";
+	mv $(CPP_MINIMIZER_FASTQ_ERROR) $(EXECUTABLE_DIR);
+	parallel "$(TIME) $(EXECUTABLE_DIR)/$(CPP_MINIMIZER_FASTQ_ERROR) $(DATA_DIR)/sd_merged_"{1}".maf.gz > $(RESULTS_DIR)/$(CPP_MINIMIZER_FASTQ_ERROR)-"{1}".txt 2>&1" ::: 85 90 95 99
+
+######################################################################
+# INDEXING
+######################################################################
+lcpTrieIndexing:
+	@echo "Compiling $(LCP_TRIE_BASED)$(CXX)";
+	$(GXX) -Wall -o $(LCP_TRIE_BASED) $(LCP_TRIE_BASED)$(CXX) -lz; 
+	@echo "Moving $(LCP_TRIE_BASED) to $(EXECUTABLE_DIR)";
+	mv $(LCP_TRIE_BASED) $(EXECUTABLE_DIR) && \
+	parallel "$(TIME) $(EXECUTABLE_DIR)/$(LCP_TRIE_BASED) $(DATA_DIR)/sd_merged_"{}".fastq.gz $(RESULTS_DIR)/sd_merged_"{}"_trie.gfa > $(RESULTS_DIR)/$(LCP_TRIE_BASED)-"{}".txt 2>&1" ::: 85 90 95 99;
+
+lcpInvertedIndexing:;
+	@echo "Compiling $(LCP_INVERTED_BASED)$(CXX)";
+	$(GXX) -Wall -o $(LCP_INVERTED_BASED) $(LCP_INVERTED_BASED)$(CXX) -lz;
+	@echo "Moving $(LCP_INVERTED_BASED) to $(EXECUTABLE_DIR)";
+	mv $(LCP_INVERTED_BASED) $(EXECUTABLE_DIR);
+	$(TIME) $(EXECUTABLE_DIR)/$(LCP_INVERTED_BASED) $(DATA_DIR)/simulated.fastq.gz $(RESULTS_DIR)/simulated-inverted-result.gfa;
+
+######################################################################
+# OTHER
+######################################################################
+compareGFAs:
+	@echo "Compiling $(COMPARE_GFA)$(CXX)";
+	$(GXX) -Wall -g -o $(COMPARE_GFA) $(COMPARE_GFA)$(CXX);
+	@echo "Moving $(COMPARE_GFA) to $(EXECUTABLE_DIR)";
+	mv $(COMPARE_GFA) $(EXECUTABLE_DIR) && \
+	$(TIME) $(EXECUTABLE_DIR)/$(COMPARE_GFA) $(RESULTS_DIR)/sd_merged_99_gold.gfa $(RESULTS_DIR)/sd_merged_99_trie.gfa;
+
+extractChrom:
+	@echo "Compiling $(EXTRACT_CHROM)$(CXX)";
+	$(GXX) -Wall -o $(EXTRACT_CHROM) $(EXTRACT_CHROM)$(CXX) -lz;
+	@echo "Moving $(EXTRACT_CHROM) to $(EXECUTABLE_DIR)";
+	mv $(EXTRACT_CHROM) $(EXECUTABLE_DIR) && \
+	parallel --link "$(TIME) $(EXECUTABLE_DIR)/$(EXTRACT_CHROM) $(DATA_DIR)/sd_merged_"{1}".fastq.gz $(RESULTS_DIR)/$(EXTRACT_CHROM)_"{1}"_chrom_"{2}".fastq.gz "{2} ::: 85 90 95 99 ::: 2;
